Console.WriteLine("Input Number a");
int a = int.Parse(Console.ReadLine());
Console.WriteLine("Input Number b");
int b = int.Parse(Console.ReadLine());
Console.WriteLine("Input Number c");
int c = int.Parse(Console.ReadLine());
int max =  a;
if (b>max) max=b;
if(c>max) max=c;
Console.WriteLine("Max Number");
Console.WriteLine(max);
